version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - evaluacionyalutec-network
  kafka:
    container_name: kafka-eventos
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-eventos:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    networks:
      - evaluacionyalutec-network
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongosecret
    networks:
      - evaluacionyalutec-network
  crudproductos:
      container_name: crudproductos
      build:
        context: ./crudproductos # Ruta al directorio que contiene el Dockerfile
        dockerfile: Dockerfile    # Nombre del Dockerfile (opcional si es "Dockerfile")
      ports:
        - "3000:3000"
      networks:
      - evaluacionyalutec-network
      environment:
      - MONGO_URI=admin:mongosecret@mongodb:27017/
      - KAFKA_URI=kafka-eventos:9092
      depends_on:
      - mongodb
      - kafka
  consumerservice:
      container_name: consumerservice
      build:
        context: ./consumerEvaluacion/consumerEvaluacion
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
      - evaluacionyalutec-network
      environment:
      - MONGO_URI=admin:mongosecret@mongodb:27017/
      - KAFKA_URI=kafka-eventos:9092
      depends_on:
      - mongodb
      - kafka
  bff:
      container_name: bff
      build:
        context: ./bff-frontend
        dockerfile: Dockerfile
      ports:
        - "4000:4000"
      networks:
      - evaluacionyalutec-network
      environment:
      - PRODUCTOS_URI=http://crudproductos:3000
      - EVENTOS_URI=http://consumerservice:8080
      depends_on:
      - consumerservice
      - crudproductos

networks:
  evaluacionyalutec-network:
    driver: bridge
    name: evaluacionyalutec-network